name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{AKIAW3MEDDQG4ZYMMGPM }}
        AWS_SECRET_ACCESS_KEY: ${{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}}
        AWS_REGION: 'us-east-1'
        EC2_INSTANCE_ID: ${{i-0d71bb19171a37e53 }}
        EC2_USER: 'ec2-user'
      run: |
        zip -r my-web-app.zip .
        scp -o StrictHostKeyChecking=no -i my-key.pem my-web-app.zip $EC2_USER@${{ secrets.EC2_PUBLIC_DNS }}:/home/$EC2_USER/
        ssh -o StrictHostKeyChecking=no -i my-key.pem $EC2_USER@${{ secrets.EC2_PUBLIC_DNS }} 'unzip my-web-app.zip -d /var/www/html/ && sudo systemctl restart nginx'
